#!/bin/sh

if [ "$1" = "configure" ]; then
    echo "Regenerating xorg.conf"
    /usr/bin/nvidia-xconfig -s -a --force-generate --allow-empty-initial-configuration \
        --cool-bits=12 --registry-dwords="PerfLevelSrc=0x2222" \
        --no-sli --connected-monitor="DFP-0" -o /etc/X11/xorg.conf

    echo "Applying GPU timeout patch"
    sed -i '/Driver/a     Option         "Interactive" "False"' /etc/X11/xorg.conf
fi
